### ISSUE TITLE
user name and password?

### ISSUE THREAD

**Issue by oakes8585** [chaosjester/materialtix#1]
What is the default username and password for the web ui? Or does taxiti have one of its own? Ive looked on google and had really no luck. Only to find the login as user:user and password:pass im using version 1.99 of Taxiti and need a little direction the theam looks great from what ive seen just like to be able to use it............

**Comment by chaosjester** [comment]
Hey, you set the username and password in the Tixati settings, under the Web Interface options there is a big text box for them.

The format is username/password.

**Comment by oakes8585** [comment]
Thank you
